/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hansung_band_cctv_util_NDKAdapter */

#ifndef _Included_com_example_hansung_band_cctv_util_NDKAdapter
#define _Included_com_example_hansung_band_cctv_util_NDKAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    setDataSource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_setDataSource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_play
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    stop
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_stop
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    setDataSource1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_setDataSource1
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    play1
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_play1
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_hansung_band_cctv_util_NDKAdapter
 * Method:    stop1
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_hansung_band_1cctv_util_NDKAdapter_stop1
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
